FROM python:3.6.4

COPY . /app
WORKDIR /app
RUN pip install -r requirements.txt

ENTRYPOINT ["python"]
CMD ["elastic_control.py"]

RUN chmod +x ./load_documents.sh
ENTRYPOINT [ "./load_documents.sh" ]